Newsletter option added, footer modified, cleaned markdown links
tankala/learn-pip-trends pull request #12
Opened 2023-11-08 07:35 UTC by ayushjain01

2023-11-08 09:07 UTC, tankala requested changes
In footer links which are there in header not needed. In footer we need to give option to subscribe to newsletter.

Please add "piptrends home" link in the header

2023-11-08 09:18 UTC, ayushjain01 commented
Made the required changes

2023-11-08 10:09 UTC, tankala requested changes
Need to add widget which will take mail id and subscribe in footer where it mentions pip trends newsletter. This embed script also mentioned in the ticket.

newsletter.md is missing redirect_to

2023-11-08 10:34 UTC, ayushjain01 commented
unable to change bg colour for substack iframe
newsletter.md has redirect_to

2023-11-08 10:40 UTC, tankala requested changes
Decrease the height. unnecessary white space coming.
Mention that it is for pip trends newsletter

2023-11-08 10:53 UTC, ayushjain01 commented
Unable to override default padding and background colour
![image](https://github.com/tankala/learn-pip-trends/assets/67141217/248017bb-6a71-4e94-9340-f10d74c15001)

2023-11-08 11:49 UTC, tankala requested changes
Will explain over the call. In footer previous one is good but size need to be decreased. I just wanted to add pip Trends newsletter text that's it.
Current one is bulky.

2023-11-09 09:57 UTC, ayushjain01 commented
Substack does not have an API, so it's little difficult to modify the signup form.
https://substackapi.com/ is an alternative but requires one additional step to sign up, which can result in lesser conversions. 
Buttondown has an api, but even that requires an email verification to sign up.
I'm trying to build something of our own to make it easier to subscribe on substack itself. 
This is how the footer looks for now-
![image](https://github.com/tankala/learn-pip-trends/assets/67141217/356044a5-fc85-476e-a65a-bde62914fdf2)

2023-11-09 11:43 UTC, tankala commented on _includes/footer.html
> +      <p>Join our mailing list. Subscribe to pip Trends Weekly Newsletter.</p>
Change the text to "Stay Ahead of the Curve: Get the Pip Trends Weekly Digest!"

2023-11-09 11:46 UTC, tankala commented on _includes/aside/toc.html
> +        <br>
Here it takes the user to the newsletter so this button not required. On top anyway we have newsletter option in menu level.

2023-11-09 11:47 UTC, tankala requested changes
Please look into comments

2023-11-09 13:12 UTC, tankala approved these changes

2023-11-09 13:15 UTC, tankala requested changes
In mobile view subscribe to news it's not looking good check once.
The message and the newsletter should be in the same white box so that people will it is for that.
If possible put the pip Trends part or whole subscribe message in the green color just like our theme.

2023-11-10 05:57 UTC, tankala requested changes

2023-11-10 05:57 UTC, tankala commented on _includes/footer.html
> +    <center>
Only this part needs to be white. Rest keep as it is because this section and other sections seem like merged.

2023-11-10 09:12 UTC, tankala approved these changes

2023-11-10 09:12 UTC, merged