BeautifulSoup4 article added
tankala/learn-pip-trends pull request #17
Opened 2023-12-12 09:45 UTC by Aman-Clement

2023-12-12 09:47 UTC, ayushjain01 requested changes
Good to go.
Image file names are inconsistent

2023-12-13 13:32 UTC, ayushjain01 requested changes

2023-12-13 13:32 UTC, ayushjain01 commented on _data/authors.yml
> +aman:
No need to add in authors.yml anymore, you can add directly in the front matter

2023-12-14 12:57 UTC, ayushjain01 approved these changes

2023-12-14 12:57 UTC, ayushjain01 commented on _gettingstarted/beautifulsoup4.md
> +aman:
Change this to author

2023-12-14 12:57 UTC, ayushjain01 approved these changes

2023-12-21 12:33 UTC, tankala approved these changes

2023-12-21 12:33 UTC, tankala commented on _data/authors.yml
> +
now authors.yml not required

2023-12-21 12:34 UTC, merged