getting started with requests
tankala/learn-pip-trends pull request #21
Opened 2024-01-08 07:05 UTC by Aman-Clement

2024-01-08 09:21 UTC, ayushjain01 commented
[assets/images/getting-started/getting-started-requests-cover.png](https://github.com/tankala/learn-pip-trends/pull/21/files#diff-e8bf5c3828c73df71664c270b6b5bf70e5fe57716a6d7769d44fd3fda6a9a834)

Requests logo is trimmed. 
Also, you can use a different colour gradient.

2024-01-08 09:24 UTC, ayushjain01 requested changes

2024-01-08 09:24 UTC, ayushjain01 commented on _gettingstarted/requests.md
> +description: Python's requests library is a powerful and user-friendly tool for making HTTP requests
description can be more about the article, than the library. Something like "A beginner's guide to Python's requests library, a powerful and user friendly tool for making HTTP requests" could be helpful.

2024-01-09 12:31 UTC, tankala approved these changes

2024-01-09 12:31 UTC, merged