Getting Started Article - Discord.py added
tankala/learn-pip-trends pull request #30
Opened 2024-04-11 13:09 UTC by Aman-Clement

2024-04-14 09:48 UTC, ayushjain01 requested changes
Article looks good, only some minor formatting issues

2024-04-14 09:48 UTC, ayushjain01 commented on _gettingstarted/discord.md
> +```python
this should be bash not python

2024-04-14 09:48 UTC, ayushjain01 commented on _gettingstarted/discord.md
> +```python
same here

2024-04-14 09:48 UTC, ayushjain01 commented on _gettingstarted/discord.md
> +```
Add > before ```

2024-04-14 09:48 UTC, ayushjain01 commented on _gettingstarted/discord.md
> +> your categories may differ based on your requirement, this is just defining the structure
Note*

2024-04-14 09:48 UTC, ayushjain01 commented on _gettingstarted/discord.md
> +In this article we have laid the basic foundation for the discord bot, but the possibilities are endless, we can work with voice commands, various decorators, error handling, manage members. Discord.
You can add faqs and related articles within the same article

2024-05-27 14:02 UTC, tankala approved these changes

2024-05-27 14:02 UTC, merged